apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-oidc-proxy-audit-policy
  namespace: kube-oidc-proxy-ns
data:
  audit.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    rules:
    - level: Metadata
  webhook.yaml: |
    # apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: http://127.0.0.1:8082/events/kubernetes
      name: logstash
    contexts:
    - context:
        cluster: logstash
        user: ""
      name: default-context
    current-context: default-context
    preferences: {}
    users: []
